---
name: Publish Book
on:
  # Manually trigger workflow
  workflow_dispatch:

  # Run work flow conditional on linter workflow success
  workflow_run:
    workflows:
      - "MegaLinter"
    paths:
      - "docs/**"
      - "includes/**"
      - "overrides/**"
      - "mkdocs.yaml"
    branches:
      - main
    types:
      - completed

permissions:
  contents: write

jobs:
  publish-book:
    name: MkDocs Publish
    runs-on: ubuntu-latest
    steps:
      - run: echo "🚀 Job automatically triggered by ${{ github.event_name }}"
      - run: echo "🐧 Job running on ${{ runner.os }} server"
      - run: echo "🐙 Using ${{ github.ref }} branch from ${{ github.repository }} repository"

      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          sparse-checkout: |
            docs
            includes
            overrides
      - run: echo "🐙 ${{ github.repository }} repository sparse-checkout to the CI runner."

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - run: pip install mkdocs-material mkdocs-callouts mkdocs-glightbox mkdocs-git-revision-date-localized-plugin mkdocs-redirects pillow cairosvg
      - run: mkdocs gh-deploy --force
      - run: echo "🐙 ."

      # Summary and status
      - run: echo "🎨 MkDocs Publish Book workflow completed"
      - run: echo "🍏 Job status is ${{ job.status }}."
